all:
	pdflatex ActiveSubspace_MD_paper 
	bibtex ActiveSubspace_MD_paper
	pdflatex ActiveSubspace_MD_paper
	pdflatex ActiveSubspace_MD_paper
	pdflatex ActiveSubspace_MD_paper

clean:

	rm -f *.toc *.aux *.log *.bbl *.blg *.pdf *.out

